School_Online/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from School_Online import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_module.urls')),
    path('contact-us', include('contact_module.urls')),
    path('courses', include('course_module.urls')),
    path('register/', include('user_module.urls')),
    path('cart',include('cart_module.urls')),
    path('backup/',include('backup_module.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart_module/urls.py
from django.urls import path
from .views import AddToCartView, CartView, RemoveFromCartView

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:pk>/', AddToCartView.as_view(), name='add-to-cart'),
    path('remove/<int:pk>/', RemoveFromCartView.as_view(), name='remove-from-cart'),
]

user_module/urls.py
from django.urls import path
from . import views

app_name= "user"
urlpatterns = [
    path('sign-up', views.RegisterView.as_view(), name='register'),
    path('forget_password/', views.ForgetPasswordView.as_view(), name='forget_password'),
    path('sign-in', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('reset_password/<str:activation_code>',views.ResetPasswordView.as_view(),name= "reset-password"),
    path('user-activation/<str:activation_code>',views.UserActivateView.as_view(),name= "user_activation")


    ]

user_module/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    activation_code = models.CharField(max_length=200, verbose_name='ایمیل فعال سازی')

    class Meta:
        verbose_name_plural = 'کاربران'
        verbose_name = 'کاربر'

user_module/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError

from user_module.models import User


class RegisterForm(forms.Form):
    email = forms.CharField(label="ایمیل",
                            widget=forms.TextInput(attrs={
                                'class': 'req',
                                'placeholder': "ایمیل",
                                'name': 'email',
                                'type': "email"
                            })),
    password = forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={
            'class': 'signup-form',
            'type': "password",
            'placeholder': "رمـز عبـور",
        }))
    confirm_password = forms.CharField(
        label='تایید رمز عبور',
        widget=forms.PasswordInput(attrs={
            'class': 'signup-form',
            'type': "password",
            'placeholder': "تایید رمـز عبـور",
        }))

    # def clean_username(self):
    #     username = self.cleaned_data.get("username")
    #     user: User = User.objects.filter(username__iexact=username)
    #
    #     if user :
    #         raise ValidationError('کاربری با این نام وجود دارد')


class LoginForm(forms.Form):
    email = forms.EmailField(
        label='آدرس ایمیل',
        widget=forms.EmailInput(attrs={
            'class': 'login-form',
            'type': "email",
            'placeholder': "آدرس ایمیل",

        }))
    password = forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={
            'class': 'login-form',
            'type': "password",
            'placeholder': "رمـز عبـور",
        }))


class ForgetPassForm(forms.Form):
    email = forms.EmailField(
        label='آدرس ایمیل',
        widget=forms.EmailInput(attrs={
            'class': 'login-form',
            'type': "email",
            'placeholder': "آدرس ایمیل",

        }))


class ResetPasswordForm(forms.Form):
    password = forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={
            'class': 'signup-form',
            'type': "password",
            'placeholder': "رمـز عبـور",
        }))
    confirm_password = forms.CharField(
        label='تایید رمز عبور',
        widget=forms.PasswordInput(attrs={
            'class': 'signup-form',
            'type': "password",
            'placeholder': "تایید رمـز عبـور",
        }))

user_module/views.py
from django.contrib.auth import login, logout
from django.http import Http404, HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.views.generic import CreateView
from django.views.generic.base import View
from utils.email_service import send_mail
from user_module.forms import RegisterForm, LoginForm, ForgetPassForm, ResetPasswordForm
from user_module.models import User


# Create your views here.

class RegisterView(View):

    def get(self, request):
        register_form = RegisterForm()
        login_form = LoginForm()
        context = {
            "register_form": register_form
        }
        return render(request, 'user_module/register_form.html', context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            email_user = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user: bool = User.objects.filter(email__iexact=email_user).first()

            if user:
                form.add_error("email", 'حسابی با این مشخصات موجود است')
            else:
                new_user = User(email=email_user, activation_code=get_random_string(5), is_active=False,
                                username=email_user)
                new_user.set_password(password)
                new_user.save()
                send_mail("ایمیل فعال سازی",{"user" : user},"user_module/email/activate_mail.html",new_user.email,)
                return redirect(reverse('user:login'))
        context = {
            "register_form": form
        }
        return render(request, 'user_module/register_form.html', context)


class UserActivateView(View):
    def get(self, request, activation_code):
        user: User = User.objects.get(activation_code__iexact=activation_code)
        if not user.is_active:
            if user:
                user.is_active = True
                user.save()
                return redirect(reverse('user:login'))
            raise Http404
        else:  # todo : user is already active !
            pass


class LoginView(View):
    def get(self, request):
        login_form = LoginForm()
        context = {
            'login_form': login_form
        }

        return render(request, 'user_module/login_form.html', context)

    def post(self, request: HttpRequest):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_email = login_form.cleaned_data.get('email')
            user_pass = login_form.cleaned_data.get('password')
            user: User = User.objects.filter(email__iexact=user_email).first()
            if user is not None:
                if not user.is_active:
                    login_form.add_error('email', 'حساب کاربری شما فعال نشده است')
                else:
                    is_password_correct = user.check_password(user_pass)
                    if is_password_correct:
                        login(request, user)
                        return redirect(reverse('home:home_page'))
                    else:
                        login_form.add_error('email', 'کلمه عبور اشتباه است')
            else:
                login_form.add_error('email', 'کاربری با مشخصات وارد شده یافت نشد')

        context = {
            'login_form': login_form
        }

        return render(request, 'user_module/login_form.html', context)


class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect(reverse("home:home_page"))

class ForgetPasswordView(View):
    def get(self, request):
        forget_pass_form = ForgetPassForm()
        context = {
            "forget_form": forget_pass_form
        }
        return render(request, "user_module/forget_password.html", context)

    def post(self, request):
        forget_pass_form = ForgetPassForm(request.POST)
        if forget_pass_form.is_valid():
            email = forget_pass_form.cleaned_data.get("email")
            user: User = User.objects.filter(email__iexact=email).first()
            if user is not None :
                forget_pass_form.add_error("email", "کاربری با این ایمیل وجود ندارد")
            send_mail("ایمیل فعال سازی", {"user": user}, "user_module/email/reset_code.html", user.email )
            return redirect(reverse("user:reset-password"))

        context = {
            "forget_form": forget_pass_form
        }
        return render(request, "user_module/forget_password.html", context)



class ResetPasswordView(View):
    def get(self, request: HttpRequest, activation_code):
        user: User = User.objects.filter(activation_code__iexact=activation_code).first()
        if user is None:
            return redirect(reverse('user:login'))

        reset_pass_form = ResetPasswordForm()

        context = {
            'reset_pass_form': reset_pass_form,
            'user': user
        }
        return render(request, 'user_module/reset_password.html', context)

    def post(self, request: HttpRequest, activation_code):
        reset_pass_form = ResetPasswordForm(request.POST)
        user: User = User.objects.filter(activation_code__iexact=activation_code).first()
        if reset_pass_form.is_valid():
            if user is None:
                return redirect(reverse('user:login'))
            user_new_pass = reset_pass_form.cleaned_data.get('password')
            user.set_password(user_new_pass)
            user.activation_code = get_random_string(72)
            user.is_active = True
            user.save()
            return redirect(reverse('user:login'))

        context = {
            'reset_pass_form': reset_pass_form,
            'user': user
        }

        return render(request, 'user_module/reset_password.html', context)

user_module/templates/user_module/forget_password.html
{% extends 'shared/index.html' %}

{% block title %}
    ورود
{% endblock %}
{% block body %}
<body id="contact" class="page">


    <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-6 col-md-offset-3">
                    <div class="login-form"><!--sign up form-->
                        <h2>فراموشی رمز عبور</h2>
                        <form method="post" action="{% url 'user:forget_password' %}">
                            {% csrf_token %}
                            {{ forget_form }}



                            <button type="submit" class="btn btn-default">فراموشی رمز عبور</button>
                        </form>
                    </div><!--/sign up form-->
                </div>
            </div>
        </section>
    </div>
{% endblock %}

user_module/templates/user_module/login_form.html
{% extends 'shared/index.html' %}

{% block title %}
    ورود
{% endblock %}
{% block body %}
<body id="contact" class="page">


    <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-6 col-md-offset-3">
                    <div class="signup-form"><!--sign up form-->
                        <h2>ورود به حساب کاربری</h2>
                        <form method="post" action="{% url 'user:login' %}">
                            {% csrf_token %}
                            {{ login_form }}
                            <p><a href="{% url "user:forget_password" %}">رمز عبور را فراموش کردم</a></p>


                            <button type="submit" class="btn btn-default">ورود</button>
                        </form>
                    </div><!--/sign up form-->
                </div>
            </div>
        </section>
    </div>
{% endblock %}

user_module/templates/user_module/register_form.html
{% extends 'shared/index.html' %}

{% block title %}
    register
{% endblock %}

{% block body %}
    <body id="contact" class="page">
<div class="page-heading text-center">
    <div class="container">
      <h2> ثبت نام </h2>
    </div>
  </div>
  <div class="container success">
    <h4> ثبت نام کاربر</h4>
    <form method="post" class="contact">
        {% csrf_token %}
      <div class="row">
                <div class="col-sm-6 col-md-offset-3">
						<form method="post" action="{% url 'user:register' %}" >
                            {% csrf_token %}
                            {{ register_form }}
      <div class="row clearfix">
        <div class="col-sm-12">
          <div class="pull-right">
            <button type="submit" name="submit" class="greybutton">ارسال</button>
          </div>
        </div>
      </div>
    </form>
  </div>
      </div></form></div>
{% endblock %}

user_module/templates/user_module/reset_password.html
{% extends 'shared/index.html' %}


{% block title %}بازیابی کلمه عبور{% endblock %}

{% block body %}
    <body id="contact" class="page">
    <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-6 col-md-offset-3">
                    <div class="signup-form"><!--sign up form-->
                        <h2>بازیابی کلمه عبور</h2>
                        <form method="post" action="{% url 'user:reset-password' activation_code=user.activation_code %}">
                            {% csrf_token %}
                            {{ reset_pass_form.password.label_tag }}
                            {{ reset_pass_form.password }}
                              {{ reset_pass_form.confirm_password.label_tag }}
                            {{ reset_pass_form.confirm_password }}

                            <button type="submit" class="btn btn-default">بازیابی کلمه عبور</button>
                        </form>
                    </div><!--/sign up form-->
                </div>
            </div>
        </section>
    </div>
{% endblock %}