School_Online/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from School_Online import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_module.urls')),
    path('contact-us', include('contact_module.urls')),
    path('courses', include('course_module.urls')),
    path('register/', include('user_module.urls')),
    path('cart',include('cart_module.urls')),
    path('backup/',include('backup_module.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backup_module/urls.py
from django.urls import  path
from . import  views
app_name = "backup"
urlpatterns = [
    path('info',views.InfoView.as_view(),name="info-page")
]

cart_module/urls.py
from django.urls import path
from .views import AddToCartView, CartView, RemoveFromCartView

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:pk>/', AddToCartView.as_view(), name='add-to-cart'),
    path('remove/<int:pk>/', RemoveFromCartView.as_view(), name='remove-from-cart'),
]

contact_module/urls.py
from django.urls import path
from . import views

app_name= "contact"
urlpatterns = [
path('', views.ContactUsView.as_view(), name='contact-us')
]

home_module/urls.py
from django.urls import path
from .views import Home_page
app_name = "home"
urlpatterns = [
    path('', Home_page.as_view() ,name='home_page')
]

user_module/urls.py
from django.urls import path
from . import views

app_name= "user"
urlpatterns = [
    path('sign-up', views.RegisterView.as_view(), name='register'),
    path('forget_password/', views.ForgetPasswordView.as_view(), name='forget_password'),
    path('sign-in', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('reset_password/<str:activation_code>',views.ResetPasswordView.as_view(),name= "reset-password"),
    path('user-activation/<str:activation_code>',views.UserActivateView.as_view(),name= "user_activation")


    ]

templates/shared/footer-refernces.html
<script src="/static/assets/libs/jquery/jquery.js"></script> 
<script src="/static/assets/libs/bootstrap/js/bootstrap.min.js"></script> 
<script src="/static/assets/libs/rslides/responsiveslides.min.js"></script> 
<script src="/static/assets/libs/jquery-ui/jquery-ui.min.js"></script> 
<script src="/static/assets/libs/slick/slick.min.js"></script> 
<script src="/static/assets/js/main.js"></script>

templates/shared/header_references.html
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>مائده لرن</title>
<link rel="stylesheet" href="/static/assets/libs/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/assets/libs/material-design-iconic-font/css/material-design-iconic-font.min.css">
<link rel="stylesheet" href="/static/assets/libs/jquery-ui/jquery-ui.min.css">
<link rel="stylesheet" href="/static/assets/libs/rslides/responsiveslides.css">
<link rel="stylesheet" href="/static/assets/libs/slick/slick.css">
<link rel="stylesheet" href="/static/assets/css/main.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600%7CMontserrat:300,400,600%7CRaleway:300,400,400i,600%7COpen+Sans:400,400i%7CVarela+Round">
<link rel="stylesheet" type="text/css" href="/static/style.css">
<link rel="stylesheet" type="text/css" href="/static/assets/css/animate.css">
<script src="/static/assets/js/jquery-3.2.1.min.js"></script>
<script src="/static/assets/js/wow.min.js"></script>
<script>
              new WOW().init();
</script>

templates/shared/index.html
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'shared/header_references.html' %}
    <title>{% block title%} {% endblock %}</title>
</head>
{% render_partial 'home_module.views.header_component' %}
{% block header_slider %}{% endblock %}
{% block body %}{% endblock %}
{% render_partial 'home_module.views.footer_component' %}

{% include 'shared/footer-refernces.html' %}
</body>
</html>

templates/shared/site_footer-component.html
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6 col-xs-12">
        <h1 class="logo float-none"><a class="no-text-decoration-white" href="index.html">مائده لرن</a></h1>
        <ul class="contactinfo">
          <li class="address"><strong>آدرس: </strong>تهران , خیابان جمهوری , پلاک , مجتمع یاس , طبقه هفتم , واحد دوم , شرکت مائده لرن</li>
          <li class="phone"><strong>تلفن تماس: </strong>+989109999999</li>
          <li class="email"><strong>پست الکترونیکی: </strong> info@maedelearn.ir</li>
        </ul>
        <ul class="social">
          <li><a href="#"><i class="zmdi zmdi-facebook"></i></a></li>
          <li> <a href="#"><i class="zmdi zmdi-twitter"></i></a></li>
          <li> <a href="#"><i class="zmdi zmdi-google-old"></i></a></li>
          <li> <a href="#"><i class="zmdi zmdi-pinterest"></i></a></li>
          <li> <a href="#"><i class="zmdi zmdi-instagram"></i></a></li>
          <li> <a href="#"><i class="zmdi zmdi-rss"></i></a></li>
        </ul>
      </div>
      <div class="col-md-2 col-sm-6 col-xs-12">
        <h6>راهنمای سایت</h6>
        <ul class="information">
          <li><a href="#">راهنما و سوالات متداول</a></li>
          <li><a href="#">دوره های ویدویی</a></li>
          <li><a href="#">سفارش آنلاین</a></li>
          <li><a href="#">پشتیبانی آنلاین</a></li>
        </ul>
      </div>
      <div class="col-md-2 col-sm-6 col-xs-12">
        <h6>اطلاعات</h6>
        <ul class="information">
          <li><a href="#">درباره ما</a></li>
          <li><a href="#">خدمات ما</a></li>
          <li><a href="#">تاریخچه خرید</a></li>
          <li><a href="#">اطلاعات</a></li>
        </ul>
      </div>
      <div class="col-md-2 col-sm-6 col-xs-12">
        <h6>حساب من</h6>
        <ul class="information">
          <li><a href="#">پلان ها و قیمت ها</a></li>
          <li><a href="#">مورد علاقه ها</a></li>
          <li><a href="#">اطلاعات شخصی</a></li>
          <li><a href="#">ورود</a></li>
        </ul>
      </div>
      <div class="col-md-2 col-sm-12 col-xs-12">
        <h6>دسترسی سریع</h6>
        <ul class="information">
          <li><a href="#">آموزش های ویدیویی</a></li>
          <li><a href="#">دوره های آنلاین</a></li>
          <li><a href="#">مدرس شوید</a></li>
          <li><a href="#">تماس با ما</a></li>
        </ul>
      </div>
    </div>
    <div class="row botbar">
      <div class="col-sm-7 float-right">
        <p class="copyright">&copy;      کپی رایت 2017 مائده لرن - تمامی حقوق برای شرکت آموزشی مائده لرن محفوظ است.</p>
      </div>
      <div class="col-sm-5">
        <ul class="pull-right payments">
          <li><a href="#"><img src="/static/assets/img/payments/1.png" alt="Payment"></a></li>
          <li><a href="#"><img src="/static/assets/img/payments/2.png" alt="Payment"></a></li>
          <li><a href="#"><img src="/static/assets/img/payments/3.png" alt="Payment"></a></li>
          <li><a href="#"><img src="/static/assets/img/payments/4.png" alt="Payment"></a></li>
          <li><a href="#"><img src="/static/assets/img/payments/5.png" alt="Payment"></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer><!--/Footer-->

templates/shared/site_header_component.html
<header>
  <ul class="pull-right lang">
    <li class="selected"><a href="#">EN</a></li>
    <li><a href="#">DE</a></li>
    <li><a href="#">FR</a></li>
    <li><a href="#">PO</a></li>
  </ul>
  <div class="container">
    <div id="topbar">
      <div class="pull-right">
        <div class="navigation">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar"> <i class="zmdi zmdi-menu zmdi-hc-lg"></i> </button>
          <nav class="collapse navbar-collapse" id="myNavbar">
            <ul>
              <li class="active"> <a href="{% url "home:home_page" %}">خانه</a>
                <ul class="submenu submenu-list">
                  <li><a href="index.html">صفحه اصلی 1</a></li>
                  <li><a href="index2.html">صفحه اصلی 2</a></li>
                  <li><a href="index3.html">صفحه اصلی 3</a></li>
                </ul>
              </li>
              <li> <a href="#">دوره های آنلاین</a>
                <ul class="submenu clearfix">
                  <li>
                    <ul class="sub-column">
                      <li><a href="#">همه دوره ها (817)</a></li>
                      <li><a href="#">کسب و کار ها (18)</a></li>
                      <li><a href="#">سیستم مدیریت محتوا (14)</a></li>
                      <li><a href="#">طراحی (17)</a></li>
                      <li><a href="#">توسعه (23)</a></li>
                      <li><a href="#">علوم انسانی (19)</a></li>
                    </ul>
                  </li>
                  <li>
                    <ul class="sub-column">
                      <li><a href="#">پزشکی (8)</a></li>
                      <li><a href="#">موزیک (47)</a></li>
                      <li><a href="#">فتوگرافی (68)</a></li>
                      <li><a href="#">فتوشاپ (87)</a></li>
                      <li><a href="#">ای تی و نرم افزار (41)</a></li>
                      <li><a href="#">سبک زندگی (54)</a></li>
                    </ul>
                  </li>
                  <li>
                    <ul class="sub-column">
                      <li><a href="#">شیمی (54)</a></li>
                      <li><a href="#">زبان (83)</a></li>
                      <li><a href="#">کسب و کار (52)</a></li>
                      <li><a href="#">سئو (39)</a></li>
                      <li><a href="#">بازاریابی (44)</a></li>
                      <li><a href="#">ارائه ویدیویی (33)</a></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li> <a href="#">دسته بندی ها</a>
                <ul class="submenu submenu-list">
                  <li><a href="categories.html">دسته بندی ها</a></li>
                  <li><a href="courses-3-col.html">دوره ها 3 ستونه</a></li>
                  <li><a href="courses-4-col.html">دوره ها 4 ستونه</a></li>
                  <li><a href="courses-gallery.html">گالری دوره ها</a></li>
                  <li><a href="course-single.html">دوره تکی</a></li>
                  <li><a href="courses-list.html">لیست دوره ها</a></li>
                  <li><a href="courses-sidebar.html">دوره ها با سایدبار</a></li>
                </ul>
              </li>
              <li> <a href="#">پشتیبانی</a>
                <ul class="submenu submenu-list">
                  <li><a href="{% url "backup:info-page" %}">چگونه کار میکند</a></li>
                  <li><a href="pricing.html">قیمت ها</a></li>
                  <li><a href="services-1.html">خدمات 1</a></li>
                  <li><a href="services-2.html">خدمات 2</a></li>
                  <li><a href="teachers.html">مدرسین</a></li>
                  <li><a href="teacher-single.html">مدرسین تکی</a></li>
                  <li><a href="blog-single.html">نوشته تکی</a></li>
                  <li><a href="blog.html">بلاگ</a></li>
                </ul>
              </li>
              <li><a href="{% url "contact:contact-us" %}">تماس با ما</a></li>
            </ul>
          </nav>
        </div>
          {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
                    <a href="/admin" class="register"> پنل ادمین</a>
              {% endif %}
              <a href="{% url "user:logout" %}" class="register">خروج</a>
                      <div class="cart"> <a href="#"><i class="zmdi zmdi-case zmdi-hc-lg"></i><span>2</span></a>
          <div class="cart-container">
            <h6>سبد خرید (2)</h6>
            <div class="cart-item clearfix"> <img src="/static/assets/img/cart1.jpg" alt="cart item" class="pull-left"> <a href="#">چگونه یک طراح UX شویم</a>
              <p class="quantity">1x $35,500</p>
              <button class="remove">x حذف</button>
            </div>
            <div class="cart-item clearfix"> <img src="/static/assets/img/cart2.jpg" alt="cart item" class="pull-left"> <a href="#">8 گام به راه اندازی استارت اپ خودتان</a>
              <p class="quantity">1x $18,700</p>
              <button class="remove">x حذف</button>
            </div>
            <div class="cart-controls text-center"> <a href="#" class="checkout">پرداخت</a> <a href="#" class="viewcart">نمایش سبد</a> <a href="#" class="addcourse">افزودن دوره</a> </div>
          </div>
        </div>
          {% else %}
        <a href="{% url 'user:login' %}" class="blueplay login">ورود</a>
          <a href="{% url "user:register" %}" class="register">ثبت نام</a>
            {% endif %}
        <div class="search"> <a href="#" class="search"><i class="zmdi zmdi-search zmdi-hc-lg"></i></a>
          <div class="search-something">
            <input type="search" placeholder="دنبال چه چیزی هستید؟">
            <a href="#"><i class="zmdi zmdi-search"></i></a> </div>
        </div>
      </div>
      <h1 class="logo"><a class="no-text-decoration-white" href="{% url "home:home_page" %}">
        <h1>مائده لرن</h1>
        </a></h1>
    </div>
  </div>
</header>